### ISSUE TITLE
Chore: create a file structure 

### ISSUE THREAD

**Issue by Petsamuel** [newtoallofthis123/htmler#1]
create a file structure such that all CSS and JS files Have their own folder

**Comment by newtoallofthis123** [comment]
But remember, you have to use tailwindcss cli to convert the `input.css` to `tailwind.css`. If you can do that , sure I'll assign it to you

**Comment by Petsamuel** [comment]
hmm, it's worth trying.

**Comment by Petsamuel** [comment]
@newtoallofthis123 I'm done with this issue, should I go ahead and create a PR?
or should I wait until the HacktoberFest officially starts.

my reasons

![image](https://github.com/newtoallofthis123/htmler/assets/65086865/9f58edae-c273-4594-aeb6-9a884a8b18cc)

**Comment by newtoallofthis123** [comment]
Wait for October.....
