### ISSUE TITLE
fix: Improve the Buttons Ui

### ISSUE THREAD

**Issue by Petsamuel** [newtoallofthis123/htmler#2]
Hover effects provide users with immediate visual feedback that an element on the webpage is interactive. When a user hovers over a button, it changes appearance, indicating that it can be clicked or interacted with.

**Comment by newtoallofthis123** [comment]
Can you be a bit specific? Which buttons do you mean? Include screenshots

**Comment by Krish-Panchani** [comment]
Hey, I like to work on this Issue. 
Assign me.

**Comment by newtoallofthis123** [comment]
Sure @Krish-Panchani, but first can you please include that improvements to the buttons UI? Any screenshot or idea in the head would be good. Just improve is a bit vague, don't you think.

**Comment by Petsamuel** [comment]
> Can you be a bit specific? Which buttons do you mean? Include screenshots

![image](https://github.com/newtoallofthis123/htmler/assets/65086865/3552e1bd-aad6-4526-b23a-b1746f94ba61)
this buttons doesn't have any form of user interactivity, i had to check the console to be sure I clicked on the button

**Comment by newtoallofthis123** [comment]
That's actually true 😄. 

One thing though, will you be able to work on both the issues you open simultaneously? How about I assign @Krish-Panchani for this and you to #1?

**Comment by Krish-Panchani** [comment]
> Sure @Krish-Panchani, but first can you please include that improvements to the buttons UI? Any screenshot or idea in the head would be good. Just improve is a bit vague, don't you think. 

Hover effects and Icons based on button name.

**Comment by newtoallofthis123** [comment]
@Petsamuel  @Krish-Panchani how about you both work on this issue? Since I have already assigned on for each of you, I think it's only fair that you both have access to this.

**Comment by Petsamuel** [comment]
Master @Krish-Panchani how do you intend to add icon to these buttons? I don't think it's that necessary.

**Comment by Petsamuel** [comment]
kindly add hacktocber-accepted badge to my PR

**Comment by newtoallofthis123** [comment]
Done
