### ISSUE TITLE
Add Open Graphs, Meta tags & Description 

### ISSUE THREAD

**Issue by Krish-Panchani** [newtoallofthis123/htmler#4]
Add open graph & meta tags for improve social sharing.
Open Graphs tags controls what content displays when sharing links on social media.

**Comment by newtoallofthis123** [comment]
Good Luck with the meta tags. I am assigning you to the issue. However, please keep in mind the brand you portray through the meta description. Any queries, please feel free to reach out

**Comment by coderhuBypassion** [comment]
Hey, can you plz help me in understanding what exactly the issue is.?

**Comment by newtoallofthis123** [comment]
Well, you see, each website has some open graph and meta tags that are used by search engines and social media apps to scrap and represent your app. Think of the banners that load when you post a link on Discord or whatsapp or even twitter.

Here are some resources for you to explore them 

https://www.w3schools.com/tags/tag_meta.asp
https://www.searchenginewatch.com/2018/04/04/a-quick-and-easy-guide-to-meta-tags-in-seo/

**Comment by coderhuBypassion** [comment]
Thank you so much mate for explaining the issue! Now I get it.

**Comment by newtoallofthis123** [comment]
Cool :)
