### ISSUE TITLE
Feature Request: Implement an alert message prompt

### ISSUE THREAD

**Issue by Petsamuel** [newtoallofthis123/htmler#5]
the alert message is aimed to displaying a message when an action triggered it. 
for example, when the copy button is clicked an alert notification would display.

**Comment by newtoallofthis123** [comment]
I mean, isn't it the same as your button interactivity issue? Why don't you try integrating this into that itself? It is very much related

#2

**Comment by Petsamuel** [comment]
I would like to work on this 
Assign to me!
